typography_spectrum: 0.43302116729319096
color:
  saturation: 0.8459908852819353
  brandStrength: 0.43174344836734235
  rhythmicContrast: 0.04828111850656569
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  lightness: 0.25030154339037836
layout_spectrum: 0.00825497042387724
name: Webb and Co.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Furniture for Life
