layout_spectrum: 0.5112782
typography_spectrum: 0.29374154284596443
color:
  saturation: 0.12499732174910605
  brandStrength: 0.1435214343946427
  lightness: 0.662580887787044
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  rhythmicContrast: 0.6571753080934286
name: Webb and Co.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Webb & Co.
description: Furniture for Life
