color:
  saturation: 0.9938927565235645
  brandStrength: 0.2801446837838739
  rhythmicContrast: 0.7026315780822188
  brandColors:
    - '#10222B'
    - '#95AB63'
    - '#BDD684'
    - '#E2F0D6'
    - '#F6FFE0'
  lightness: 0.0877516430336982
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.00825497042387724
typography_spectrum: 0.8494993296917528
name: Webb and Co.
