typography_spectrum: 0.1453634
color:
  saturation: 0.6303184
  brandStrength: 0.2937501231208444
  lightness: 0.3591906
  brandColors:
    - '#B0CC99'
    - '#677E52'
    - '#B7CA79'
    - '#F6E8B1'
    - '#89725B'
  rhythmicContrast: 0.5627292
layout_spectrum: 0.5193929
name: Webb and Co.
navigation:
  - name: Cool Stuff
    id: a96cdae1-f242-460b-8c2d-e9d1ec05fe7b
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Webb & Co.
description: Furniture for Life
