typography_spectrum: 0.6378446
color:
  saturation: 0.1203008
  brandStrength: 0.5732469772920012
  lightness: 0.3270677
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  rhythmicContrast: 0.9594392
layout_spectrum: 0.5112782
name: Webb and Co.
navigation:
  - name: Humble Beginnings
    id: 79dc49e7-be6e-4a3e-b2d3-ae6d51daafa0
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Webb & Co.
description: Furniture for Life
