color:
  saturation: 0.10926197865046561
  brandStrength: 0.8911774614825845
  rhythmicContrast: 0.8380746482871473
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  lightness: 0.02817392465658486
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.00825497042387724
typography_spectrum: 0.5643449628259987
name: Webb and Co.
